### ISSUE TITLE
All examples are now Java files? 

### ISSUE THREAD

**Issue by alexfgreen** [diwi/PixelFlow#10]
was this intentional? shouldn't they be .pde files?

**Comment by diwi** [comment]
The github repository is java only so that it can be used for creating a project in a Java-IDE, like Eclipse, for developing.

New library releases (... for processing, compiled jar, pde-examples, reference, src) can be found here:
https://github.com/diwi/PixelFlow/releases

you can download the zip (PixelFlow.zip) and install the processing library manually or use the contribution manager of the Processing-IDE.
