### ISSUE TITLE
Set OpenGL device for systems with integrated gpu

### ISSUE THREAD

**Issue by DasPez** [diwi/PixelFlow#3]
Hi,
PixelFlow uses my integrated GPU as default. Is there a way to change this?
` 
## PixelFlow v0.21 

```
OPENGL_VENDOR:         Intel
OPENGL_RENDERER:       Intel(R) HD Graphics 530
OPENGL_VERSION:        4.4.0 - Build 20.19.15.4454
GLSLVersionString:     #version 440 core
GLSLVersionNumber:     4.40.0
GLVersion:             4.4 (Core profile, arb, compat[ES2, ES3], FBO, hardware) - 4.4.0 - Build 20.19.15.4454
GLVendorVersionNumber: 20.19.15 (- Build 20.19.15.4454)
```

---

`
I would like to use a NVIDIA GTX960M

**Comment by diwi** [comment]
hey,

have a look in your nvidia control panel. I think you can modify the application profiles, e.g. for processing, to switch between integrated vs. dedicated graphics.

It looks like for Processing the profile is set (or no profile is set at all, and the default is just integrated), so that always the integrated graphics devices (intel HD graphics) is chosen. Which makes sketches that use shaders, or opengl in general, quite slow, especially compared to your gtx960m.

let me know if you figured out something.

**Comment by diwi** [comment]
maybe you find here something:
Nvidia Control Panel > Manage 3d settings > select preferred graphics processor

**Comment by diwi** [comment]
this thread might also be useful:
https://www.reddit.com/r/techsupport/comments/2fxpxx/minecraft_uses_intel_hd_instead_of_nvidia_gpu/

**Comment by DasPez** [comment]
changing application profiles did not work ("javaw.exe" and "processing.exe") but "select preferred graphics processor" in the global settings  fixed it!
Thank you
